server:
  port: 8888

spring:
  application:
    name: GATEWAY
  cloud:
    discovery:
      enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10